require('dotenv').config();

const { createClient } = require('@supabase/supabase-js');

const url = process.env.SUPABASE_URL || '';
const key = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

async function main() {
  if (!url.trim() || !key.trim()) {
    console.error('STOP: Supabase admin configuration missing.');
    process.exitCode = 1;
    return;
  }

  const client = createClient(url, key, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
  });

  const path =
    'privacy-test/' +
    Date.now().toString() +
    '-private-chat-test.txt';

  const body = Buffer.from(
    'Astro Soul Path private chat attachment verification',
    'utf8',
  );

  try {
    const { error: uploadError } = await client.storage
      .from('chat')
      .upload(path, body, {
        contentType: 'text/plain',
        upsert: false,
      });

    if (uploadError) {
      console.error('UPLOAD TEST ERROR:', uploadError.message);
      process.exitCode = 1;
      return;
    }

    console.log('TEST OBJECT UPLOADED');
    console.log('path:', path);

    const { data: publicData } = client.storage
      .from('chat')
      .getPublicUrl(path);

    const publicUrl = publicData?.publicUrl ?? '';

    console.log('public URL generated by helper:', Boolean(publicUrl));

    if (publicUrl) {
      const publicResponse = await fetch(publicUrl);

      console.log('direct public HTTP status:', publicResponse.status);

      if (publicResponse.ok) {
        console.error(
          'FAIL: private chat object is publicly downloadable.',
        );
        process.exitCode = 1;
        return;
      }

      console.log('PASS: direct public access denied');
    }

    const { data: signedData, error: signedError } =
      await client.storage
        .from('chat')
        .createSignedUrl(path, 60);

    if (signedError || !signedData?.signedUrl) {
      console.error(
        'SIGNED URL ERROR:',
        signedError?.message ?? 'No signed URL',
      );
      process.exitCode = 1;
      return;
    }

    const signedResponse = await fetch(signedData.signedUrl);

    console.log('signed HTTP status:', signedResponse.status);

    if (!signedResponse.ok) {
      console.error('FAIL: signed private access did not work.');
      process.exitCode = 1;
      return;
    }

    const text = await signedResponse.text();

    console.log(
      'signed content correct:',
      text.includes(
        'Astro Soul Path private chat attachment verification',
      ),
    );

    console.log('PASS: signed private access works');
  } finally {
    await client.storage
      .from('chat')
      .remove([path])
      .catch(() => undefined);

    console.log('TEST OBJECT CLEANED UP');
  }
}

main()
  .catch((error) => {
    console.error(
      'UNEXPECTED ERROR:',
      error?.message ?? String(error),
    );
    process.exitCode = 1;
  })
  .finally(() => {
    setTimeout(
      () => process.exit(process.exitCode ?? 0),
      100,
    );
  });
